version: "3.7"

volumes:
  nginx:
  redis:
  neo4j:
  mongo:
  node_modules:
  
services:
  data:
    container_name: ${PROJECT_NAME}_data
    build:
      context: .
      dockerfile: config/docker/data.dockerfile
    env_file:
      - ./.env
    networks:
      - utila-coffee-network
    volumes:
      - nginx:/data/nginx
      - redis:/data/redis
      - neo4j:/data/neo4j
      - mongo:/data/mongo
      - node_modules:/data/server/node_modules
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    build:
      context: .
      dockerfile: config/docker/nginx.dockerfile
    cap_drop: 
      - ALL
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
    depends_on:
      - data
      - graphql
    env_file:
      - ./.env
    networks: 
      - utila-coffee-network
    volumes:
      - ./public:/var/www/public/:delegated
      - nginx:/var/cache/nginx
  redis:
    container_name: ${PROJECT_NAME}_redis
    restart: always
    build: 
      context: .
      dockerfile: config/docker/redis.dockerfile
    depends_on:
      - data
    env_file:
      - ./.env
    networks:
      - utila-coffee-network
    ports: 
      - "6379:6379"
    volumes:
      - redis:/data
  neo4j:
    container_name: ${PROJECT_NAME}_neo4j
    restart: always
    image: bitnami/neo4j
    depends_on:
      - data
    env_file:
      - ./.env
    networks:
      - utila-coffee-network
    ports: 
      - "7687:7687"
    volumes: 
      - neo4j:/bitnami/neo4j
  mongo:
    container_name: ${PROJECT_NAME}_mongo
    restart: always
    image: bitnami/mongodb
    depends_on:
      - data
    env_file:
      - ./.env
    networks: 
      - utila-coffee-network
    ports:
      - "27017:27017"
    volumes:
      - mongo:/bitnami/mongo
  graphql:
    container_name: ${PROJECT_NAME}_graphql
    restart: always
    build: 
      context: .
      dockerfile: config/docker/dev.dockerfile
    depends_on:
      - data
    env_file:
      - ./.env 
    networks: 
      - utila-coffee-network
    volumes:
      - ./.build/server:/usr/app/server:delegated
      - node_modules:/usr/app/node_modules
networks:
  utila-coffee-network:
    driver: bridge
